/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdata;


import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdelfatah Ibrahim
 */
public class StudentData2 extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel model = new DefaultTableModel();
    public StudentData2() {
        
        initComponents();
        
       Object col[] = {"student_iD","Course_code","Maths","English","Biology","Computing","Chemistry","Physics","AddMaths","Bussines","TotaScore","Average","Ranking"};
       model.setColumnIdentifiers(col);
       jTable1.setModel(model);
        conn = StudentData2.ConnectDB();
        
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtchem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtphysics = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcomp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTscore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtaverage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtranking = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtmath = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtenglish = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtbio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtkiswahili = new javax.swing.JTextField();
        txtbusiness = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 224, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 12), "STUDENT RECORDS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Course Code:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        txtchem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtchem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtchemKeyTyped(evt);
            }
        });
        jPanel1.add(txtchem, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Student_id:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 30));

        txtphysics.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtphysics.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphysicsKeyTyped(evt);
            }
        });
        jPanel1.add(txtphysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Computer:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, 30));

        txtcomp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcomp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcompKeyTyped(evt);
            }
        });
        jPanel1.add(txtcomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Total Score:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 30));

        txtTscore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtTscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Average:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 30));

        txtaverage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtaverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Ranking:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 30));

        txtranking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Student_id:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 30));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Firstname:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 170, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Chemistry:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, 30));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Math:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, 30));

        txtmath.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtmath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmathActionPerformed(evt);
            }
        });
        txtmath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmathKeyTyped(evt);
            }
        });
        jPanel1.add(txtmath, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 130, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("English:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 30));

        txtenglish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtenglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenglishActionPerformed(evt);
            }
        });
        txtenglish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtenglishKeyTyped(evt);
            }
        });
        jPanel1.add(txtenglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 130, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Biology");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 30));

        txtbio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtbio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbioKeyTyped(evt);
            }
        });
        jPanel1.add(txtbio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 130, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Surnamame:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIT00", "CCS00", "CCT00", "CCT00", "ICTM00" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 170, 30));

        txtkiswahili.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtkiswahili.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkiswahiliKeyTyped(evt);
            }
        });
        jPanel1.add(txtkiswahili, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 130, -1));

        txtbusiness.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtbusiness.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbusinessKeyTyped(evt);
            }
        });
        jPanel1.add(txtbusiness, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 130, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Kiswahili");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Business:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Physics:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 770, 470));

        jPanel2.setBackground(new java.awt.Color(176, 224, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 12), "TRANSCRIPT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 450, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 490, 470));

        jButton1.setBackground(new java.awt.Color(95, 158, 160));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1087, 640, 130, -1));

        jButton2.setBackground(new java.awt.Color(95, 158, 160));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 640, 130, -1));

        jButton3.setBackground(new java.awt.Color(95, 158, 160));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Delete");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 170, -1));

        jButton4.setBackground(new java.awt.Color(95, 158, 160));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Transcript");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 180, -1));

        jButton5.setBackground(new java.awt.Color(95, 158, 160));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Student Result");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_ID", "Course_Code", "Math", "Biology", "Computer", "Chemistry", "Physics", "English", "Kiswahili", " Business", "Total_Score", "Average ", "Ranking"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1230, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public static Connection ConnectDB(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolsystem","root","");
            System.out.println("Connected Successfully");
            return conn;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
        
    
}
    
    
    private void txtenglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenglishActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      this.getContentPane().setBackground(new java.awt.Color(176,224,230));
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtmathKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmathKeyTyped
        char iNumber = evt.getKeyChar();
        
        if(!(Character.isDigit(iNumber))
            || (iNumber == KeyEvent.VK_BACK_SPACE)
                    || (iNumber == KeyEvent.VK_DELETE)){
             evt.consume();
    }
                    
                
                
    }//GEN-LAST:event_txtmathKeyTyped

    private void txtenglishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtenglishKeyTyped
       char iNumber = evt.getKeyChar();
       
       if(!(Character.isDigit(iNumber))
               ||(iNumber == KeyEvent.VK_BACK_SPACE)
               ||(iNumber == KeyEvent.VK_DELETE)
               ||(iNumber == KeyEvent.VK_BACK_SPACE)){
           evt.consume();
       }
    }//GEN-LAST:event_txtenglishKeyTyped

    private void txtbioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbioKeyTyped
         char iNumber = evt.getKeyChar();
       
       if(!(Character.isDigit(iNumber))
               ||(iNumber == KeyEvent.VK_BACK_SPACE)
               ||(iNumber == KeyEvent.VK_DELETE)
               ||(iNumber == KeyEvent.VK_BACK_SPACE)){
           evt.consume();
       }
    }//GEN-LAST:event_txtbioKeyTyped

    private void txtcompKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompKeyTyped
        char iNumber = evt.getKeyChar();
       
       if(!(Character.isDigit(iNumber))
               ||(iNumber == KeyEvent.VK_BACK_SPACE)
               ||(iNumber == KeyEvent.VK_DELETE)
               ||(iNumber == KeyEvent.VK_BACK_SPACE)){
           evt.consume();
       }
    }//GEN-LAST:event_txtcompKeyTyped

    private void txtchemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtchemKeyTyped
         char iNumber = evt.getKeyChar();
       
       if(!(Character.isDigit(iNumber))
               ||(iNumber == KeyEvent.VK_BACK_SPACE)
               ||(iNumber == KeyEvent.VK_DELETE)
               ||(iNumber == KeyEvent.VK_BACK_SPACE)){
           evt.consume();
       }
    }//GEN-LAST:event_txtchemKeyTyped

    private void txtphysicsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphysicsKeyTyped
         char iNumber = evt.getKeyChar();
       
       if(!(Character.isDigit(iNumber))
               ||(iNumber == KeyEvent.VK_BACK_SPACE)
               ||(iNumber == KeyEvent.VK_DELETE)
               ||(iNumber == KeyEvent.VK_BACK_SPACE)){
           evt.consume();
       }
    }//GEN-LAST:event_txtphysicsKeyTyped

    private void txtbusinessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusinessKeyTyped
         char iNumber = evt.getKeyChar();
       
       if(!(Character.isDigit(iNumber))
               ||(iNumber == KeyEvent.VK_BACK_SPACE)
               ||(iNumber == KeyEvent.VK_DELETE)
               ||(iNumber == KeyEvent.VK_BACK_SPACE)){
           evt.consume();
       }
    }//GEN-LAST:event_txtbusinessKeyTyped

    private void txtkiswahiliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkiswahiliKeyTyped
        char iNumber = evt.getKeyChar();
       
       if(!(Character.isDigit(iNumber))
               ||(iNumber == KeyEvent.VK_BACK_SPACE)
               ||(iNumber == KeyEvent.VK_DELETE)
               ||(iNumber == KeyEvent.VK_BACK_SPACE)){
           evt.consume();
       }
    }//GEN-LAST:event_txtkiswahiliKeyTyped
    private JFrame frame;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Student Result System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        JTextField temp = null;
        for(Component c:jPanel1.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                temp=(JTextField)c;
                temp.setText(null);
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        
//                String id = rs.getString(1);
//                String firstname = rs.getString(2);
//                String lastname = rs.getString(3);
//                String balance = rs.getString(4);
//                
//                jLabel2.setText(id.trim());
//                jLabel4.setText(firstname.trim());
//                jLabel6.setText(lastname.trim());
//                jLabel11.setText(balance.trim());
                
        double[] R = new double[14];
        R[0] = Double.parseDouble(txtmath.getText());
        R[1] = Double.parseDouble(txtenglish.getText());
        R[2] = Double.parseDouble(txtbio.getText());
        R[3] = Double.parseDouble(txtcomp.getText());
        R[4] = Double.parseDouble(txtchem.getText());
        R[5] = Double.parseDouble(txtphysics.getText());
        R[6] = Double.parseDouble(txtbusiness.getText());
        R[7] = Double.parseDouble(txtkiswahili.getText());
       
        R[8] = (R[0]+R[1]+R[2]+R[3]+R[4]+R[5]+R[6]+R[7]) / 8;
        R[9] = (R[0]+R[1]+R[2]+R[3]+R[4]+R[5]+R[6]+R[7]);
          
        
//        double Totalscore = R[9];
//        double Average = R[8];
       
         String average = String.format("%.0F", R[8]);
       txtaverage.setText(average);
        
        String TotalScore = String.format("%.0F", R[9]);
       txtTscore.setText(TotalScore);
        
        if(R[9] >= 700){
            txtranking.setText("First class");
        }
        else if(R[9] >= 600){
            txtranking.setText("2nd class upper");
        }
         else if(R[9] >= 500){
            txtranking.setText("2nd class lower");
        }
         else if(R[9] >= 400){
            txtranking.setText("pass");
        }
         else if(R[9] >= 300){
            txtranking.setText("fail");
        }
        
        

        
       //====================================================================================================================
        
        String sql = "Insert into student(student_ID,Course_code,Maths,English,Biology,Computing,Chemistry,Physics,"
                +"AddMaths,Bussines,TotalScore,Average,Ranking)values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
        try{
            pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.setString(1,txtId.getText()); 
            pst.setString(2, (String) jComboBox1.getSelectedItem());
            pst.setString(3,txtmath.getText());
            pst.setString(4,txtenglish.getText());
            pst.setString(5,txtbio.getText());
            pst.setString(6,txtcomp.getText());
            pst.setString(7,txtchem.getText());
            pst.setString(8,txtphysics.getText());
            pst.setString(9,txtbusiness.getText());
            pst.setString(10,txtkiswahili.getText());
            pst.setString(11,txtTscore.getText());
            pst.setString(12,txtaverage.getText());
            pst.setString(13,txtranking.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "New Record Added");
            rs.close();
            
            
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
             System.out.println(e);
        }
     
       
//        String sq = "Select TotalScore,Average,Ranking from students";
//        try {
//     
//            pst = (PreparedStatement) conn.prepareStatement(sq);
//            rs = pst.executeQuery();
//            String Totalscore = rs.getString(1);
//            String Average = rs.getString(2);
//            String Ranking = rs.getString(3);
//            
//      
//          
//        } catch (SQLException ex) {
//            Logger.getLogger(StudentData.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtmathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmathActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void updateTable(){
        
        conn = StudentData2.ConnectDB();
        if(conn !=null){
            
        
        String sql = "Select student_ID,Course_code,Maths,English,Biology,Computing,Chemistry,Physics,AddMaths,Bussines,TotalScore,Average,Ranking from students";
        try{
             pst =  (PreparedStatement) conn.prepareStatement(sql);
             rs = pst.executeQuery();
             Object[] columnData = new Object[13];
             
             while(rs.next()){
                 columnData[0] = rs.getString("student_ID");
                 columnData[1] = rs.getString("Course_code");
                 columnData[2] = rs.getString("Maths");
                 columnData[3] = rs.getString("English");
                 columnData[4] = rs.getString("Biology");
                 columnData[5] = rs.getString("Computing");
                 columnData[6] = rs.getString("Chemistry");
                 columnData[7] = rs.getString("Physics");
                 columnData[8] = rs.getString("AddMaths");
                 columnData[9] = rs.getString("Bussines");
                 columnData[10] = rs.getString("TotalScore");
                 columnData[11] = rs.getString("Average");
                 columnData[12] = rs.getString("Ranking");
                 
                 model.addRow(columnData);
             }
        } 
       
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
    }
    
        }
    
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentData2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentData2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentData2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentData2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentData2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTscore;
    private javax.swing.JTextField txtaverage;
    private javax.swing.JTextField txtbio;
    private javax.swing.JTextField txtbusiness;
    private javax.swing.JTextField txtchem;
    private javax.swing.JTextField txtcomp;
    private javax.swing.JTextField txtenglish;
    private javax.swing.JTextField txtkiswahili;
    private javax.swing.JTextField txtmath;
    private javax.swing.JTextField txtphysics;
    private javax.swing.JTextField txtranking;
    // End of variables declaration//GEN-END:variables
}
